version: "3"
services:
  app:
    container_name: nodebackend
    depends_on:
      - redis
    build: ./server
    volumes:
      - ./server/src/:/usr/src/app/src
    ports: 
    - "3000:3000"
    networks:
    - redis

  redis:
    container_name: redis-container
    image: "redis:latest"
    ports:
    - "6379:6379"
    volumes:
      - ./data:/data
    networks:
    - redis
    command: ['--requirepass "secret"']
networks:
  redis:
    driver: bridge